// Code generated by proto-gen-go-kratos-selector. DO NOT EDIT.
// versions:
// proto-gen-go-kratos-selector v0.1

package v1

import (
	context "context"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

var (
	CartjwtSelectedMethods = make(map[string]struct{})
)

func init() {

	CartjwtSelectedMethods[`/cart.service.v1.Cart/GetCart`] = struct{}{}
	CartjwtSelectedMethods[`/cart.service.v1.Cart/DeleteCart`] = struct{}{}
	CartjwtSelectedMethods[`/cart.service.v1.Cart/AddItem`] = struct{}{}
	CartjwtSelectedMethods[`/cart.service.v1.Cart/UpdateItem`] = struct{}{}
	CartjwtSelectedMethods[`/cart.service.v1.Cart/DeleteItem`] = struct{}{}
}
